spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1/test?serverTimezone=Asia/Seoul
    username: test
    password: test1!
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  jwt:
    secret: jwtsecrethostingjwtsecrethostingjwtsecrethostingjwtsecrethostingjwtsecrethosting